title: Zuko's Blog
description: Exploring code, mathematics, and digital consciousness
github_username: CuriousCaliBoi

# Email and twitter are optional:
email: rs6121@nyu.edu  
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Set baseurl to an empty string if your site is at the root (recommended for GitHub Pages)
baseurl: ""
url: "https://curiouscaliboi.github.io"

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# Exclude specific directories or files if needed (optional)
exclude:
  - .DS_Store
  - node_modules
  - vendor
  - _drafts

# Custom CSS
sass:
  sass_dir: assets/css
  style: compressed